### ISSUE TITLE
Error encountered in running the scripts at the read me

### ISSUE THREAD

**Issue by promiseve** [allenai/RL4LMs#9]
Hi , 
Following your readme scripts, i ran into an error after executing "!python scripts/training/train_text_generation.py --config_path scripts/task_configs/summarization/t5_ppo.yml"
While I identify the first 4 lines that might be from my current TensorFlow library, does anyone have some advice? 

The error is given below 
,,,
2022-10-09 01:13:11.489647: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-10-09 01:13:11.945129: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2022-10-09 01:13:13.866126: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2022-10-09 01:13:13.866414: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2022-10-09 01:13:13.866456: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
[10/09/22 01:13:18] DEBUG    2022-10-09 01:13:18,221      ]8;id=937946;file:///home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/urllib3/connectionpool.py\connectionpool.py]8;;\:]8;id=758244;file:///home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/urllib3/connectionpool.py#1003\1003]8;;\
                             [DEBUG] Starting new HTTPS                         
                             connection (1):                                    
                             huggingface.co:443                                 
                    DEBUG    2022-10-09 01:13:18,301       ]8;id=611467;file:///home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/urllib3/connectionpool.py\connectionpool.py]8;;\:]8;id=165305;file:///home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/urllib3/connectionpool.py#456\456]8;;\
                             [DEBUG]                                            
                             [https://huggingface.co:443](https://huggingface.co:443</span%3E)                         
                             "HEAD /t5-base/resolve/main/t                      
                             okenizer_config.json                               
                             HTTP/1.1" 404 0                                    
                    DEBUG    2022-10-09 01:13:18,309      ]8;id=749344;file:///home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/urllib3/connectionpool.py\connectionpool.py]8;;\:]8;id=742820;file:///home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/urllib3/connectionpool.py#1003\1003]8;;\
                             [DEBUG] Starting new HTTPS                         
                             connection (1):                                    
                             huggingface.co:443                                 
                    DEBUG    2022-10-09 01:13:18,373       ]8;id=656859;file:///home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/urllib3/connectionpool.py\connectionpool.py]8;;\:]8;id=289329;file:///home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/urllib3/connectionpool.py#456\456]8;;\
                             [DEBUG]                                            
                             [https://huggingface.co:443](https://huggingface.co:443</span%3E)                         
                             "HEAD /t5-base/resolve/main/c                      
                             onfig.json HTTP/1.1" 200 0                         
                    DEBUG    2022-10-09 01:13:18,384      ]8;id=794412;file:///home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/urllib3/connectionpool.py\connectionpool.py]8;;\:]8;id=582880;file:///home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/urllib3/connectionpool.py#1003\1003]8;;\
                             [DEBUG] Starting new HTTPS                         
                             connection (1):                                    
                             huggingface.co:443                                 
                    DEBUG    2022-10-09 01:13:18,454       ]8;id=78827;file:///home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/urllib3/connectionpool.py\connectionpool.py]8;;\:]8;id=233936;file:///home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/urllib3/connectionpool.py#456\456]8;;\
                             [DEBUG]                                            
                             [https://huggingface.co:443](https://huggingface.co:443</span%3E)                         
                             "HEAD /t5-base/resolve/main/t                      
                             okenizer_config.json                               
                             HTTP/1.1" 404 0                                    
                    DEBUG    2022-10-09 01:13:18,464      ]8;id=779280;file:///home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/urllib3/connectionpool.py\connectionpool.py]8;;\:]8;id=227910;file:///home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/urllib3/connectionpool.py#1003\1003]8;;\
                             [DEBUG] Starting new HTTPS                         
                             connection (1):                                    
                             huggingface.co:443                                 
                    DEBUG    2022-10-09 01:13:18,518       ]8;id=845759;file:///home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/urllib3/connectionpool.py\connectionpool.py]8;;\:]8;id=515264;file:///home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/urllib3/connectionpool.py#456\456]8;;\
                             [DEBUG]                                            
                             [https://huggingface.co:443](https://huggingface.co:443</span%3E)                         
                             "HEAD /t5-base/resolve/main/s                      
                             piece.model HTTP/1.1" 200 0                        
                    DEBUG    2022-10-09 01:13:18,529      ]8;id=17405;file:///home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/urllib3/connectionpool.py\connectionpool.py]8;;\:]8;id=668408;file:///home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/urllib3/connectionpool.py#1003\1003]8;;\
                             [DEBUG] Starting new HTTPS                         
                             connection (1):                                    
                             huggingface.co:443                                 
                    DEBUG    2022-10-09 01:13:18,584       ]8;id=412578;file:///home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/urllib3/connectionpool.py\connectionpool.py]8;;\:]8;id=548906;file:///home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/urllib3/connectionpool.py#456\456]8;;\
                             [DEBUG]                                            
                             [https://huggingface.co:443](https://huggingface.co:443</span%3E)                         
                             "HEAD /t5-base/resolve/main/t                      
                             okenizer.json HTTP/1.1" 200 0                      
                    DEBUG    2022-10-09 01:13:18,596      ]8;id=46178;file:///home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/urllib3/connectionpool.py\connectionpool.py]8;;\:]8;id=346117;file:///home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/urllib3/connectionpool.py#1003\1003]8;;\
                             [DEBUG] Starting new HTTPS                         
                             connection (1):                                    
                             huggingface.co:443                                 
                    DEBUG    2022-10-09 01:13:18,652       ]8;id=359239;file:///home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/urllib3/connectionpool.py\connectionpool.py]8;;\:]8;id=238891;file:///home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/urllib3/connectionpool.py#456\456]8;;\
                             [DEBUG]                                            
                             [https://huggingface.co:443](https://huggingface.co:443</span%3E)                         
                             "HEAD /t5-base/resolve/main/a                      
                             dded_tokens.json HTTP/1.1"                         
                             404 0                                              
                    DEBUG    2022-10-09 01:13:18,662      ]8;id=153299;file:///home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/urllib3/connectionpool.py\connectionpool.py]8;;\:]8;id=918576;file:///home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/urllib3/connectionpool.py#1003\1003]8;;\
                             [DEBUG] Starting new HTTPS                         
                             connection (1):                                    
                             huggingface.co:443                                 
                    DEBUG    2022-10-09 01:13:18,720       ]8;id=938154;file:///home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/urllib3/connectionpool.py\connectionpool.py]8;;\:]8;id=441526;file:///home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/urllib3/connectionpool.py#456\456]8;;\
                             [DEBUG]                                            
                             [https://huggingface.co:443](https://huggingface.co:443</span%3E)                         
                             "HEAD /t5-base/resolve/main/s                      
                             pecial_tokens_map.json                             
                             HTTP/1.1" 404 0                                    
                    DEBUG    2022-10-09 01:13:18,730      ]8;id=671520;file:///home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/urllib3/connectionpool.py\connectionpool.py]8;;\:]8;id=492011;file:///home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/urllib3/connectionpool.py#1003\1003]8;;\
                             [DEBUG] Starting new HTTPS                         
                             connection (1):                                    
                             huggingface.co:443                                 
                    DEBUG    2022-10-09 01:13:18,786       ]8;id=486197;file:///home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/urllib3/connectionpool.py\connectionpool.py]8;;\:]8;id=77872;file:///home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/urllib3/connectionpool.py#456\456]8;;\
                             [DEBUG]                                            
                             [https://huggingface.co:443](https://huggingface.co:443</span%3E)                         
                             "HEAD /t5-base/resolve/main/t                      
                             okenizer_config.json                               
                             HTTP/1.1" 404 0                                    
                    DEBUG    2022-10-09 01:13:18,797      ]8;id=750980;file:///home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/urllib3/connectionpool.py\connectionpool.py]8;;\:]8;id=562466;file:///home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/urllib3/connectionpool.py#1003\1003]8;;\
                             [DEBUG] Starting new HTTPS                         
                             connection (1):                                    
                             huggingface.co:443                                 
                    DEBUG    2022-10-09 01:13:18,867       ]8;id=973142;file:///home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/urllib3/connectionpool.py\connectionpool.py]8;;\:]8;id=345840;file:///home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/urllib3/connectionpool.py#456\456]8;;\
                             [DEBUG]                                            
                             [https://huggingface.co:443](https://huggingface.co:443</span%3E)                         
                             "HEAD /t5-base/resolve/main/c                      
                             onfig.json HTTP/1.1" 200 0                         
/tigress/pe3955/RL4LMs/rl4lms/envs/text_generation/reward.py:133: FutureWarning: load_metric is deprecated and will be removed in the next major version of datasets. Use 'evaluate.load' instead, from the new library 🤗 Evaluate: https://huggingface.co/docs/evaluate
  self._metric = load_metric("rouge")
[10/09/22 01:13:19] DEBUG    2022-10-09 01:13:19,023      ]8;id=803810;file:///home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/urllib3/connectionpool.py\connectionpool.py]8;;\:]8;id=277738;file:///home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/urllib3/connectionpool.py#1003\1003]8;;\
                             [DEBUG] Starting new HTTPS                         
                             connection (1):                                    
                             s3.amazonaws.com:443                               
                    DEBUG    2022-10-09 01:13:19,107       ]8;id=615061;file:///home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/urllib3/connectionpool.py\connectionpool.py]8;;\:]8;id=719707;file:///home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/urllib3/connectionpool.py#456\456]8;;\
                             [DEBUG]                                            
                             [https://s3.amazonaws.com:443](https://s3.amazonaws.com:443</span%3E)                       
                             "HEAD /datasets.huggingface.c                      
                             o/datasets/metrics/rouge/roug                      
                             e.py HTTP/1.1" 200 0                               
                    DEBUG    2022-10-09 01:13:19,118      ]8;id=470668;file:///home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/urllib3/connectionpool.py\connectionpool.py]8;;\:]8;id=350537;file:///home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/urllib3/connectionpool.py#1003\1003]8;;\
                             [DEBUG] Starting new HTTPS                         
                             connection (1): raw.githubus                       
                             ercontent.com:443                                  
                    DEBUG    2022-10-09 01:13:19,230       ]8;id=551399;file:///home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/urllib3/connectionpool.py\connectionpool.py]8;;\:]8;id=117604;file:///home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/urllib3/connectionpool.py#456\456]8;;\
                             [DEBUG] [https://raw.githubuse](https://raw.githubuse%3C/span%3E)                      
                             rcontent.com:443 "HEAD /huggi                      
                             ngface/datasets/2.5.1/metrics                      
                             /rouge/rouge.py HTTP/1.1" 200                      
                             0                                                  
                    DEBUG    2022-10-09 01:13:19,283      ]8;id=141867;file:///home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/urllib3/connectionpool.py\connectionpool.py]8;;\:]8;id=887993;file:///home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/urllib3/connectionpool.py#1003\1003]8;;\
                             [DEBUG] Starting new HTTPS                         
                             connection (1):                                    
                             s3.amazonaws.com:443                               
                    DEBUG    2022-10-09 01:13:19,392       ]8;id=443822;file:///home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/urllib3/connectionpool.py\connectionpool.py]8;;\:]8;id=771490;file:///home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/urllib3/connectionpool.py#456\456]8;;\
                             [DEBUG]                                            
                             [https://s3.amazonaws.com:443](https://s3.amazonaws.com:443</span%3E)                       
                             "HEAD /datasets.huggingface.c                      
                             o/datasets/metrics/meteor/met                      
                             eor.py HTTP/1.1" 200 0                             
                    DEBUG    2022-10-09 01:13:19,402      ]8;id=136782;file:///home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/urllib3/connectionpool.py\connectionpool.py]8;;\:]8;id=392469;file:///home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/urllib3/connectionpool.py#1003\1003]8;;\
                             [DEBUG] Starting new HTTPS                         
                             connection (1): raw.githubus                       
                             ercontent.com:443                                  
                    DEBUG    2022-10-09 01:13:19,523       ]8;id=570482;file:///home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/urllib3/connectionpool.py\connectionpool.py]8;;\:]8;id=370600;file:///home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/urllib3/connectionpool.py#456\456]8;;\
                             [DEBUG] [https://raw.githubuse](https://raw.githubuse%3C/span%3E)                      
                             rcontent.com:443 "HEAD /huggi                      
                             ngface/datasets/2.5.1/metrics                      
                             /meteor/meteor.py HTTP/1.1"                        
                             200 0                                              
[nltk_data] Downloading package wordnet to /home/pe3955/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt to /home/pe3955/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /home/pe3955/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
                    DEBUG    2022-10-09 01:13:19,878      ]8;id=770699;file:///home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/urllib3/connectionpool.py\connectionpool.py]8;;\:]8;id=155265;file:///home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/urllib3/connectionpool.py#1003\1003]8;;\
                             [DEBUG] Starting new HTTPS                         
                             connection (1):                                    
                             s3.amazonaws.com:443                               
                    DEBUG    2022-10-09 01:13:19,953       ]8;id=330557;file:///home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/urllib3/connectionpool.py\connectionpool.py]8;;\:]8;id=601128;file:///home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/urllib3/connectionpool.py#456\456]8;;\
                             [DEBUG]                                            
                             [https://s3.amazonaws.com:443](https://s3.amazonaws.com:443</span%3E)                       
                             "HEAD /datasets.huggingface.c                      
                             o/datasets/metrics/rouge/roug                      
                             e.py HTTP/1.1" 200 0                               
                    DEBUG    2022-10-09 01:13:19,963      ]8;id=800289;file:///home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/urllib3/connectionpool.py\connectionpool.py]8;;\:]8;id=380267;file:///home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/urllib3/connectionpool.py#1003\1003]8;;\

Evaluating:   0%|                                       | 0/134 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/tigress/pe3955/RL4LMs/scripts/training/train_text_generation.py", line 66, in <module>
    main(args.config_path,
  File "/tigress/pe3955/RL4LMs/scripts/training/train_text_generation.py", line 42, in main
    trainer.train_and_eval()
  File "/tigress/pe3955/RL4LMs/rl4lms/envs/text_generation/training_utils.py", line 197, in train_and_eval
    self._evaluate_on_datapools(epoch=iter_start)
  File "/tigress/pe3955/RL4LMs/rl4lms/envs/text_generation/training_utils.py", line 183, in _evaluate_on_datapools
    evaluate_on_samples(policy=self._alg.policy,
  File "/tigress/pe3955/RL4LMs/rl4lms/envs/text_generation/evaluation_utils.py", line 39, in evaluate_on_samples
    batch_generated_texts = generate_text(
  File "/tigress/pe3955/RL4LMs/rl4lms/envs/text_generation/evaluation_utils.py", line 96, in generate_text
    generated_texts = policy.generate(tokenizer,
  File "/tigress/pe3955/RL4LMs/rl4lms/envs/text_generation/policy.py", line 297, in generate
    self.get_policy_first_device()),
  File "/tigress/pe3955/RL4LMs/rl4lms/envs/text_generation/policy.py", line 519, in get_policy_first_device
    return self._policy_model.encoder.first_device
  File "/home/pe3955/.conda/envs/rl4lm-env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1185, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'T5Stack' object has no attribute 'first_device
,,,

**Comment by rajcscw** [comment]
This seems like a version mismatch of transformers. Can you confirm if the version is transformers==4.18.0?

**Comment by promiseve** [comment]
I used print(transformers.__version__)  to confirm the version and it is 4.18.0

**Comment by promiseve** [comment]
Issue solved: 

Fix: 
Change lines 524 and 1124 in policy.py to return self._policy_model.device

**Comment by Stephanehk** [comment]
I am running into this same issue (double-checked that transformers==4.18.0). @promiseve can you elaborate on what exactly you had to change to fix this issue? I do not think our line numbers correspond.
